service: subscription-api

plugins:
  - serverless-webpack
  - serverless-offline

package:
  individually: true

custom:
  applicationName: Subsription-Api
  subscription-table: "dynamodb-arn-subscription-${self:provider.stage}"
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1
  versionFunctions: true

  environment:
    ENV: "dev"
    SUBSCRIPTION-TABLE:
      Fn::ImportValue: "${self:custom.subscription-table}"

tags:
  DEPARTMENT: "HSDP"
  TEAM: "Las Vegas"

functions:
  subscription-get:
    handler: src/controllers/subscription/subscriptionGet.main
    description: "List the subscriptions"
    memorySize: 128
    reservedConcurrency: 1
    environment:
      ComponentName: "Subscription-Get"

  subscription-post:
    handler: src/controllers/subscription/subscriptionPost.main
    description: "Create a new subscription"
    memorySize: 128
    reservedConcurrency: 1
    environment:
      ComponentName: "Subscription-Post"

